### PR TITLE
gitignore is needed in new firmware root

### PR DESCRIPTION
**Pull request by rogerclarkmelbourne**
.gitignore is needed in the new firmware root because MCUExpresso creates a .settings and Debug folders which get tracked, and also adds a file called "firmware JLink Debug.launch" as well as modifying the .cproject with the debug lunch information and other changes.
I've also added the linkerdat files to gitignore so that I can patch them with the codec binaries, and they should not get tracked and committed etc

MCUExpresso actually created the .gitignore and inserted the Debug folder, so I'm not sure why your copy of MCUExpresso didn't do this, unless perhaps the copy of the folder you use for development is not the same as the folder which MCUExpresso uses directly.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Agghh.

dat files are not being ignore.

I''ll do a new PR when its working

**Comment by talentraspel** [comment]
Maybe because the dat files are already commited as dummy files.

**Comment by rogerclarkmelbourne** [comment]
I'm not sure what you mean by dummy files. They are real files but they contain dummy data.

I'll try re-forking and making a gitignore from scratch again to see if it fixes the problem, especially as you have restructured.

**Comment by talentraspel** [comment]
Yep. The better wording is „The *.dat files that contain only dummy data.“. I mean those files and think git won’t ignore them as they are already in.

Perhaps the best way is to just rename them to „*.dat.dummy“ and update the readme that describes how to create the required *.dat files.

Or just write a tool that creates them automagically as a pre build step.

**Comment by rogerclarkmelbourne** [comment]
I think it should be possible to add them to the gitinore after they are created, as I did that with the .project file etc

I'll try re-forking and remaking the .gitignore

**Pull request closed without merging**
